name: CI
on: [push]
jobs:

  setup:
    - name: Check out code
      uses: actions/checkout@v1

  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
    - name: Run Tests
      run: make test
