name: CI
on: [push]
jobs:

  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run Tests
        run: make test

      - name: Lint code
        run: make lint

  build:
    name: Build production ready image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build docker image
        run: make image
