name: CI
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run Tests
        run: make test
